# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eBoiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eBoiler(object):
    def setupUi(self, eBoiler):
        eBoiler.setObjectName("eBoiler")
        eBoiler.resize(727, 491)
        self.CentralBox = QtWidgets.QWidget(eBoiler)
        self.CentralBox.setGeometry(QtCore.QRect(230, 160, 271, 161))
        self.CentralBox.setObjectName("CentralBox")

        self.retranslateUi(eBoiler)
        QtCore.QMetaObject.connectSlotsByName(eBoiler)

    def retranslateUi(self, eBoiler):
        _translate = QtCore.QCoreApplication.translate
        eBoiler.setWindowTitle(_translate("eBoiler", "Form"))
