# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eBoiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eBoiler_UI(object):
    def setupUi(self, eBoiler_UI):
        eBoiler_UI.setObjectName("eBoiler_UI")
        eBoiler_UI.resize(727, 491)

        self.retranslateUi(eBoiler_UI)
        QtCore.QMetaObject.connectSlotsByName(eBoiler_UI)

    def retranslateUi(self, eBoiler_UI):
        _translate = QtCore.QCoreApplication.translate
        eBoiler_UI.setWindowTitle(_translate("eBoiler_UI", "Form"))
