# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mattias_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sim(object):
    def setupUi(self, Sim):
        Sim.setObjectName("Sim")
        Sim.resize(283, 301)
        self.label = QtWidgets.QLabel(Sim)
        self.label.setGeometry(QtCore.QRect(58, 158, 77, 16))
        self.label.setObjectName("label")
        self.addBot = QtWidgets.QPushButton(Sim)
        self.addBot.setGeometry(QtCore.QRect(126, 154, 27, 24))
        self.addBot.setObjectName("addBot")
        self.removeBot = QtWidgets.QPushButton(Sim)
        self.removeBot.setGeometry(QtCore.QRect(154, 154, 27, 24))
        self.removeBot.setObjectName("removeBot")
        self.showAmountOfBots = QtWidgets.QLabel(Sim)
        self.showAmountOfBots.setGeometry(QtCore.QRect(58, 182, 55, 16))
        self.showAmountOfBots.setObjectName("showAmountOfBots")
        self.amountBotsSlider = QtWidgets.QSlider(Sim)
        self.amountBotsSlider.setGeometry(QtCore.QRect(50, 240, 160, 22))
        self.amountBotsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.amountBotsSlider.setObjectName("amountBotsSlider")
        self.label_2 = QtWidgets.QLabel(Sim)
        self.label_2.setGeometry(QtCore.QRect(50, 218, 165, 16))
        self.label_2.setObjectName("label_2")
        self.amountBotsSlider_2 = QtWidgets.QSlider(Sim)
        self.amountBotsSlider_2.setGeometry(QtCore.QRect(46, 102, 160, 22))
        self.amountBotsSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.amountBotsSlider_2.setObjectName("amountBotsSlider_2")
        self.label_3 = QtWidgets.QLabel(Sim)
        self.label_3.setGeometry(QtCore.QRect(46, 80, 165, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Sim)
        QtCore.QMetaObject.connectSlotsByName(Sim)

    def retranslateUi(self, Sim):
        _translate = QtCore.QCoreApplication.translate
        Sim.setWindowTitle(_translate("Sim", "Form"))
        self.label.setText(_translate("Sim", "Min # bots"))
        self.addBot.setText(_translate("Sim", "+"))
        self.removeBot.setText(_translate("Sim", "-"))
        self.showAmountOfBots.setText(_translate("Sim", "0"))
        self.label_2.setText(_translate("Sim", "Slider to change min bots"))
        self.label_3.setText(_translate("Sim", "Slider to change mutation"))
